### ISSUE TITLE
Ticket - Fastest path to delivering by Friday

### ISSUE THREAD

**Issue by snobbee** [Sifchain/stf-nomic-game#25]
Routes needed for playability:
/game/{game_id}/start
- joining the game is no longer allowed

/get_game/{game_id}: for discovering game state
- returns whose turn it is
- returns game state (open, in progress, concluded)

/game/{game_id}/take action: to take action according to the rules
- player action gets recorded

/game/{game_id}/end_turn
- will conclude the turn
- All players can see all actions and rule-change proposal from previous player
- Players can cast a vote until the next player ends their turn
- If majority vote passes, we roll dice (this is a part of end turn)
- the rolled dice result is added to the player's score

/game/{game_id}/list_rule_change
- lists all the accepted rule changes thus far in the game

/list_games
- lists all the games that are available to join

/game/{game_id}/rule_checker
- A way to check if the user took the right action during end-turn. This can be extremely basic for now. It can even be dummy function for now. This checker can be a Sif Agent.

voting on actions is too much complexity for now

**Comment by snobbee** [comment]
PR ready for review https://github.com/Sifchain/stf-nomic-game/pull/26/files for game status related changes

**Comment by snobbee** [comment]
New PR ready for review https://github.com/Sifchain/stf-nomic-game/pull/27 that implements the `end-turn` functionality along with submitting a new rule change and casting votes and the rule proposal and user turns lifecycle: https://github.com/Sifchain/stf-nomic-game/pull/27

all the test cases described in this file pass: https://github.com/Sifchain/stf-nomic-game/blob/feat/end-turn/tests/test_full_game_flow.py

what is completed so far:
1) Register first user
2) Login to first user
3) First user creates a new game
3.1) Check if the game was created successfully
3.2) Check if the list of games is correct
4) First user joins the new game
5) Register second user
6) Login to second user
7) Second user joins the new game
8) Login to first user again to refresh token (if necessary)
9) First user starts the game
10) First user proposes a new rule
10.1) Check if the rule proposal was created successfully
10.2) Check if the list of rule proposals is correct
10.3) Cast a vote on the rule proposal prior to the voting stage (should fail)
10.4) Second user ends turn (should fail because it's not their turn)
11) First user ends turn
11.1) Check if the rule proposal was updated to VOTING stage
11.2) Check if the rule proposal was updated to VOTING stage within the game object
12) Second user casts a vote on the rule proposal
12.1) Same user tries to vote again (should fail)
12.2) Check if the vote was recorded successfully
12.3) Check if the vote was recorded successfully within the game object
12.4) Check if the vote was recorded successfully within the game object when calling /games
13) First user casts a vote on the rule proposal
13.1) Check if the vote was recorded successfully
14) Second user proposes a new rule
14.1) Check if the rule proposal was created successfully
14.2) Check if the list of rule proposals is correct
15) Second user ends turn
15.1) Check if the rule proposal was updated to REJECTED stage
16) First user casts a vote on the rule proposal
17) Second user casts a vote on the rule proposal
17.1) Check if the rule proposal was updated
18) First user ends turn
18.1) Check if the rule proposal was updated to PASSED stage
18.2) Check if the new rule is added to the game

what is left:
* player take action endpoint for a user to play actions prior to ending turn
* end turn checks player actions and reject submitted rule proposal if any
* end turn rolls dice and add to the player score if played actions match game rules
* proposed-rule allows to override existing rule by specifying existing rule id
* end turn checks the end game criteria (first user to reach 100 points)
* deploy to OVH server
* add CI workflow for auto deploy
* add CI workflow for auto test

**Comment by snobbee** [comment]
Final PR with the remaining functionality ready for review: https://github.com/Sifchain/stf-nomic-game/pull/28

Includes those features:

- player take action endpoint for a user to play actions prior to ending turn
- end turn checks player actions and reject submitted rule proposal if any
- end turn rolls dice and add to the player score if played actions match game rules
- proposed-rule allows to override existing rule by specifying existing rule id
- end turn checks the end game criteria (first user to reach 100 points)

the test scenarios were updated to include those new features: https://github.com/Sifchain/stf-nomic-game/blob/feat/take-action-flow/tests/test_full_game_flow.py

**Comment by snobbee** [comment]
I just deployed the nomic API server to the OVH server and created this new sub domain to access to the API, you can access to the swagger UI from https://nomic-api.siftaskforce.com/docs go ahead and created an account using /register and then login to your account by clicking on Authorize
cc @jkbrooks

**Comment by jkbrooks** [comment]
Awesome, thanks @snobbee

**Comment by snobbee** [comment]
all PRs got merged
